# Generated by Django 5.1.6 on 2025-04-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeScan_app', '0003_device_estancia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='estancia',
        ),
        migrations.AddField(
            model_name='estancia',
            name='dispositivos',
            field=models.ManyToManyField(blank=True, related_name='estancias', to='homeScan_app.device'),
        ),
    ]
