# Generated by Django 5.2 on 2025-06-02 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeScan_app', '0010_alter_vulnerability_baseseverity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mueble',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muebleDispositivo', to='homeScan_app.device'),
        ),
    ]
