# Generated by Django 5.2.1 on 2025-06-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeScan_app', '0011_mueble_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estancia',
            name='tipo_suelo',
            field=models.CharField(choices=[('wood', 'Wood'), ('tile', 'Tile'), ('carpet', 'Carpet')], default='wood', max_length=20),
        ),
    ]
