# Generated by Django 5.2.1 on 2025-06-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeScan_app', '0013_alter_estancia_tipo_suelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estancia',
            name='tipo_suelo',
            field=models.CharField(choices=[('light_wood', 'Madera marrón claro'), ('tile', 'Baldosas'), ('dark_wood', 'Madera marrón oscuro')], default='light_wood', max_length=20),
        ),
    ]
