# Generated by Django 5.1.6 on 2025-04-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnet_app', '0002_connection_connectionvulnerability_device_estancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='estancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='vulnet_app.estancia'),
        ),
    ]
