# Generated by Django 5.1.6 on 2025-04-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnet_app', '0004_remove_device_estancia_estancia_dispositivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mueble',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
