# Generated by Django 5.1.6 on 2025-04-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnet_app', '0005_mueble_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mueble',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
