# Generated by Django 5.1.6 on 2025-02-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnet_app', '0014_alter_connection_first_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstancia', models.CharField(default='Sin nombre', max_length=255)),
                ('dispositivos', models.JSONField(default=list)),
            ],
        ),
    ]
