# Generated by Django 5.1.6 on 2025-02-23 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnet_app', '0014_alter_connection_first_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='formularioObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('first_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formfirstdevice', to='vulnet_app.device')),
                ('second_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formseconddevice', to='vulnet_app.device')),
                ('third_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formthirddevice', to='vulnet_app.device')),
            ],
        ),
    ]
