# Generated by Django 5.1.6 on 2025-02-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnet_app', '0015_estancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estancia',
            name='nombreEstancia',
            field=models.CharField(max_length=255),
        ),
    ]
