# Generated by Django 5.1.6 on 2025-02-24 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnet_app', '0015_formularioobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioobject',
            name='third_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formthirddevice', to='vulnet_app.device'),
        ),
    ]
