# Generated by Django 5.1.6 on 2025-03-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnet_app', '0016_alter_estancia_nombreestancia'),
        ('vulnet_app', '0016_alter_formularioobject_third_device'),
    ]

    operations = [
    ]
