# Generated by Django 5.1.6 on 2025-03-26 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnet_app', '0017_merge_20250303_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estancia',
            name='dispositivos',
        ),
        migrations.AlterField(
            model_name='estancia',
            name='nombreEstancia',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('rotation', models.FloatField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='muebles/')),
                ('estancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muebles', to='vulnet_app.estancia')),
            ],
        ),
    ]
