# Generated by Django 5.1.6 on 2025-04-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnet_app', '0018_remove_estancia_dispositivos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.TextField(unique=True),
        ),
    ]
